#
# Docker compose file for TANGO test device server.
#
# Defines:
#   - tangotest: TANGO test device server
#
# Requires: 
#   - tango.yml
#
version: '2'

services:
  tangotest:
    build:
      context: tango
      dockerfile: Dockerfile.java
    image: ska/tango-java:9.2.5a
    container_name: tangotest
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=databaseds:10000 
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - databaseds:10000
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/TangoTest 
      - test
