# 
# Docker compose file for TANGO database and database device server
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - databaseds: TANGO database device server
#
# Requires:
#   - None
#
version: '2'
volumes:
  tangodb: {}
        
services:
  tangodb:
    build:      
      context: tango
      dockerfile: Dockerfile.db
    image: ska/tangodb:9.2.5a
    container_name: tangodb      
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql

  databaseds:
    build:      
      context: tango
      dockerfile: Dockerfile.base
    image: ska/tango-base:9.2.5a
    container_name: databaseds
    hostname: databaseds
    depends_on:
      - tangodb
    environment:
      - MYSQL_HOST=tangodb:3306 
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=databaseds:10000 
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000
