#
# Docker compose file that launches an interactive iTango session.
#
# Connect to the interactive session with 'docker attach itango'.
# Disconnect with the Docker deattach sequence: <CTRL>+<P> <CTRL>+<Q>
#
# Defines:
#   - itango: iTango interactive session
#
# Requires: 
#   - tango.yml
#
version: '2'

services:
  itango:
    build:      
      context: ../docker/tango/tango-itango
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-itango:latest
    container_name: itango
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=databaseds:10000 
    stdin_open: true
    tty: true
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - databaseds:10000
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/itango3
