#
# Docker compose file that launches Astor, sending the display to a remote X11
# display.
#
# Defines:
#   - astor: service that runs Astor in a container
#   - container1: example container running Starter device
#
# Requires:
#   - tango.yml
#
version: '2'

services:
  rest:
    image: hzgde/mtangorest.docker:rc4
    container_name: ${CONTAINER_NAME_PREFIX}tango-rest
    network_mode: ${NETWORK_MODE}
    environment:
    - TANGO_HOST=${TANGO_HOST}
    - REST_API_PORT=8080
    ports:
    - "8080:8080"
