#
# Docker compose file for TANGO test device server.
#
# Defines:
#   - tangotest: TANGO test device server
#
# Requires: 
#   - tango.yml
#
version: '2'

services:
  tangotest:
    build:
      context: ../docker/tango/tango-python
    image: ${DOCKER_REGISTRY_HOSTUSER}/tango-python:latest
    container_name: tangotest
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=databaseds:10000
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - databaseds:10000
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/TangoTest
      - test

