#
# Docker compose file for TANGO database and database device server
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - databaseds: TANGO database device server
#
# Requires:
#   - None
#
version: '2'

volumes:
  archiverdb: {}

services:
  tangodb:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-db:latest
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=tango
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango

  databaseds:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-cpp:latest
    depends_on:
    - tangodb
    environment:
    - MYSQL_HOST=tangodb:3306
    - MYSQL_DATABASE=tango
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - TANGO_HOST=databaseds:10000
    entrypoint:
    - /usr/local/bin/wait-for-it.sh
    - tangodb:3306
    - --timeout=30
    - --strict
    - --
    - /usr/local/bin/DataBaseds
    - "2"
    - -ORBendPoint
    - giop:tcp::10000

  tangotest:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-java:latest
    depends_on:
    - databaseds
    environment:
    - TANGO_HOST=databaseds:10000
    entrypoint:
    - /usr/local/bin/wait-for-it.sh
    - databaseds:10000
    - --timeout=30
    - --strict
    - --
    - /usr/local/bin/TangoTest
    - test

  hdbpp-es:
    image: nexus.engageska-portugal.pt/ska-docker/tango-archiver:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}hdbpp-es
    depends_on:
      - databaseds
      - archiver-dsconfig
      - maria-db
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - HdbManager=archiving/hdbpp/confmanager01
      # TODO: FOR FUTURE REFERENCE
      #- HDB_TYPE=timescaledb
      #- HDB_NAME=hdb
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
                  find . -iname hdbppes-srv && ./usr/local/bin/hdbppes-srv 01 v5"
  # TODO: FOR FUTURE REFERENCE
  #        /bin/bash -c "
  #          echo HELLO!!!;
  #          sleep 20;
  #          wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
  #               hdbppes-srv 01"

  archiver-dsconfig:
    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
    container_name: ${CONTAINER_NAME_PREFIX}archiver-dsconfig
    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    volumes:
      - ..:/tmc-prototype
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             json2tango -w -a -u /tmc-prototype/data/archiver-devices.json &&
             sleep infinity"

  maria-db:
    image: nexus.engageska-portugal.pt/ska-docker/mariadb_hdbpp:0.1.0
    container_name: archiver-maria-db
    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - MYSQL_DATABASE=hdbpp
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=${TANGO_HOST}
    volumes:
      - archiverdb:/var/lib/mysql
    restart: on-failure
