version: '2'

volumes:
  tangodb: {}
  archiverdb: {}

services:
  tangodb:
    image: nexus.engageska-portugal.pt/ska-docker/tango-db:latest
    container_name: tangodb
#    network_mode: ${NETWORK_MODE}
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql
    restart: on-failure

  databaseds:
    image: nexus.engageska-portugal.pt/ska-docker/tango-cpp:latest
    container_name: databaseds
#    network_mode: ${NETWORK_MODE}
    depends_on:
      - tangodb
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=${TANGO_HOST}
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - ${MYSQL_HOST}
      - --timeout=60
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000
    restart: on-failure

  hdbpp-es:
      image: nexus.engageska-portugal.pt/ska-docker/tango-archiver:latest
#      network_mode: ${NETWORK_MODE}
      container_name: hdbpp-es
      depends_on:
        - databaseds
        - dsconfig
        - maria-db
      environment:
        - TANGO_HOST=${TANGO_HOST}
        - HdbManager=archiving/hdbpp/confmanager01
        #- HDB_TYPE=timescaledb
        #- HDB_NAME=hdb
      command: >
        /bin/bash -c "
          wait-for-it.sh archiver-maria-db:3306 --timeout=30 --strict --
          wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
               hdbppes-srv 01"

  hdbpp-cm:
      image: nexus.engageska-portugal.pt/ska-docker/tango-archiver:latest
 #     network_mode: ${NETWORK_MODE}
      container_name: hdbpp-cm
      depends_on:
        - databaseds
        - dsconfig
        - maria-db
      environment:
        - TANGO_HOST=${TANGO_HOST}
        - HdbManager=archiving/hdbpp/confmanager01
        #- HDB_TYPE=timescaledb
        #- HDB_NAME=hdb
      command: >
        /bin/bash -c "
          wait-for-it.sh archiver-maria-db:3306 --timeout=30 --strict --
          wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
               hdbppcm-srv 01"

  configurehdbpp:
      image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:0.1.0
#      network_mode: ${NETWORK_MODE}
      container_name: configurehdbpp
      depends_on:
        - databaseds
        - dsconfig
        - maria-db
        - hdbpp-es
        - hdbpp-cm
      environment:
        - TANGO_HOST=${TANGO_HOST}
      volumes:
        - ./scripts/configure_hdbpp.py:/configure_hdbpp.py
        - ./data/attribute_fqdn.txt:/attribute_fqdn.txt
      command: >
        /bin/bash -c "
           wait-for-it.sh archiver-maria-db:3306 --timeout=30 --strict --
           wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo chmod 777 /configure_hdbpp.py;
             /venv/bin/python /configure_hdbpp.py \
              --cm=tango://archiver-1234-databaseds:10000/archiving/hdbpp/confmanager01\
              --es=tango://archiver-1234-databaseds:10000/archiving/hdbpp/eventsubscriber01 \
              --attrfile=/attribute_fqdn.txt v4"

  tangotest:
    image: nexus.engageska-portugal.pt/tango-example/tango-example:latest
    container_name: tangotest
#    network_mode: ${NETWORK_MODE}
    depends_on:
      - dsconfig
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /usr/local/bin/TangoTest test"

  dsconfig:
    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
    container_name: dsconfig
#    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             json2tango -w -a -u /tango-archiver/data/archiver-devices.json &&
             sleep infinity"
    volumes:
      - .:/tango-archiver

  maria-db:
    image: nexus.engageska-portugal.pt/ska-docker/mariadb_hdbpp:latest
    container_name: archiver-maria-db
#    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=hdbpp
      - MYSQL_HOST=archiver-maria-db:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=${TANGO_HOST}
    restart: on-failure


