
version: '2'

services:
  tangodb:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-db:latest
    container_name: ${CONTAINER_NAME_PREFIX}tangodb
    network_mode: ${NETWORK_MODE}
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=tango
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    restart: on-failure

  databaseds:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-cpp:latest
    container_name: ${CONTAINER_NAME_PREFIX}databaseds
    network_mode: ${NETWORK_MODE}
    depends_on:
    - tangodb
    environment:
    - MYSQL_HOST=${MYSQL_HOST}
    - MYSQL_DATABASE=tango
    - MYSQL_USER=tango
    - MYSQL_PASSWORD=tango
    - TANGO_HOST=${TANGO_HOST}
    entrypoint:
    - /usr/local/bin/wait-for-it.sh
    - ${MYSQL_HOST}:3306
    - --timeout=30
    - --strict
    - --
    - /usr/local/bin/DataBaseds
    - "2"
    - -ORBendPoint
    - giop:tcp::10000
    restart: on-failure

  maria-db:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/mariadb_hdbpp:latest
    container_name: archiver-maria-db
    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=hdbpp
      - MYSQL_HOST=archiver-maria-db:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    restart: on-failure

  hdbpp-es:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-archiver:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}hdbpp-es
    depends_on:
      - databaseds
      - dsconfig
      - maria-db
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - HdbManager=archiving/hdbpp/confmanager01
    command: >
      /bin/bash -c "
        wait-for-it.sh archiver-maria-db:3306 --timeout=30 --strict --
        wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             hdbppes-srv 01"
    restart: on-failure

  hdbpp-cm:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-archiver:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}hdbpp-cm
    depends_on:
      - databaseds
      - dsconfig
      - maria-db
    environment:
      - TANGO_HOST=${TANGO_HOST}
      - HdbManager=archiving/hdbpp/confmanager01
    command: >
      /bin/bash -c "
        wait-for-it.sh archiver-maria-db:3306 --timeout=30 --strict --
        wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             hdbppcm-srv 01"
    restart: on-failure

  dsconfig:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-dsconfig:latest
    container_name: ${CONTAINER_NAME_PREFIX}dsconfig
    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             json2tango -w -a -u /tango-archiver/data/archiver-devices.json &&
             sleep infinity"
    volumes:
      - .:/tango-archiver
    restart: on-failure

  tangotest:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/tango-java:latest
    container_name: ${CONTAINER_NAME_PREFIX}tangotest
    network_mode: ${NETWORK_MODE}
    environment:
      - TANGO_HOST=${TANGO_HOST}
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - ${TANGO_HOST}
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/TangoTest
      - test
    restart: on-failure
