---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pogo-{{ template "ska-docker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pogo-{{ template "ska-docker.name" . }}
    chart: {{ template "ska-docker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pogo-{{ template "ska-docker.name" . }}/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pogo-{{ template "ska-docker.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pogo-{{ template "ska-docker.name" . }}
    chart: {{ template "ska-docker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
